ALTER SESSION SET CONTAINER = ORCLPDB1;
CREATE USER &&SV_USER IDENTIFIED BY "&&SV_PASS" DEFAULT TABLESPACE PROTHEUS_DATA QUOTA UNLIMITED ON PROTHEUS_DATA;
GRANT CONNECT, RESOURCE, DBA TO &&SV_USER;
EXIT;