#!/bin/bash
echo "⚙️ Configurando ambiente TOTVS Protheus no Oracle 21c..."

export ORACLE_SID=ORCLCDB
export ORACLE_HOME=/opt/oracle/product/21c/dbhome_1
export PATH=$ORACLE_HOME/bin:$PATH

sqlplus -s / as sysdba <<EOF
ALTER SYSTEM SET CURSOR_SHARING=EXACT SCOPE=BOTH;
ALTER SYSTEM SET PROCESSES=500 SCOPE=SPFILE;
ALTER SYSTEM SET SESSIONS=550 SCOPE=SPFILE;
ALTER SYSTEM SET MEMORY_TARGET=0 SCOPE=SPFILE;
ALTER SYSTEM SET SGA_TARGET=2G SCOPE=SPFILE;
ALTER SYSTEM SET PGA_AGGREGATE_TARGET=1G SCOPE=SPFILE;
ALTER SYSTEM SET FAST_START_MTTR_TARGET=30 SCOPE=BOTH;

ALTER SESSION SET CONTAINER = ORCLPDB1;

CREATE TABLESPACE PROTHEUS_DATA DATAFILE '/opt/oracle/oradata/protheus_data_pdb.dbf' SIZE 1G AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED;

CREATE USER ${DB_USER} IDENTIFIED BY "${DB_PASS}" DEFAULT TABLESPACE PROTHEUS_DATA QUOTA UNLIMITED ON PROTHEUS_DATA;
GRANT CONNECT, RESOURCE, DBA TO ${DB_USER};

EXIT;
EOF

echo "✅ Banco de Dados Oracle configurado e pronto para o Protheus!"