IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = '$(SQL_DB)')
BEGIN
    CREATE DATABASE [$(SQL_DB)] COLLATE Latin1_General_BIN;
END
GO

ALTER DATABASE [$(SQL_DB)] SET ALLOW_SNAPSHOT_ISOLATION ON;
ALTER DATABASE [$(SQL_DB)] SET READ_COMMITTED_SNAPSHOT ON;
GO

IF NOT EXISTS (SELECT name FROM sys.server_principals WHERE name = '$(SQL_USER)')
BEGIN
    CREATE LOGIN [$(SQL_USER)] 
        WITH PASSWORD = '$(SQL_PASS)', 
        DEFAULT_DATABASE = [$(SQL_DB)],
        CHECK_EXPIRATION = OFF,
        CHECK_POLICY = OFF;
END
GO

USE [$(SQL_DB)];
GO
IF NOT EXISTS (SELECT name FROM sys.database_principals WHERE name = '$(SQL_USER)')
BEGIN
    CREATE USER [$(SQL_USER)] FOR LOGIN [$(SQL_USER)];
    ALTER ROLE db_owner ADD MEMBER [$(SQL_USER)];
END
GO