IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = '$(SV_DBNAME)')
    CREATE DATABASE [$(SV_DBNAME)] COLLATE Latin1_General_CI_AS;
GO
IF NOT EXISTS (SELECT name FROM sys.server_principals WHERE name = '$(SV_USER)')
    CREATE LOGIN [$(SV_USER)] WITH PASSWORD = '$(SV_PASS)', DEFAULT_DATABASE = [$(SV_DBNAME)], CHECK_EXPIRATION = OFF, CHECK_POLICY = OFF;
GO
USE [$(SV_DBNAME)];
GO
IF NOT EXISTS (SELECT name FROM sys.database_principals WHERE name = '$(SV_USER)') BEGIN
    CREATE USER [$(SV_USER)] FOR LOGIN [$(SV_USER)];
    ALTER ROLE db_owner ADD MEMBER [$(SV_USER)];
END
GO